package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/operatorstack/pitot/config"
	"github.com/operatorstack/pitot/hydrate"
)

// shimDir holds the committed repo shims that make the pitot binary a
// repository property: they read .pitot/version, hydrate the pinned release
// into the user cache when absent, and exec it. No PATH binary is ever
// consulted.
const shimDir = ".pitot/bin"

// shimPOSIX is the committed POSIX shim. It carries no policy
// (the-shim-carries-no-policy): pin read, fetch, verify, exec — it never
// reads tenant fragments and never resolves a version the pin does not name
// (pin-is-the-only-version-authority).
const shimPOSIX = `#!/bin/sh
# Pitot repo shim — generated by 'pitot init'. Reads the committed pin
# (.pitot/version), hydrates that exact release into the user cache when
# absent (sha256-verified), and execs it. Upgrades rewrite the pin in a
# reviewed diff; this file never changes behavior on its own.
set -eu

here="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
pin_file="$here/.pitot/version"
if [ ! -f "$pin_file" ]; then
  echo "pitot-shim: missing $pin_file (absence-fails-closed-and-named)" >&2
  exit 1
fi
version="$(tr -d ' \t\r\n' < "$pin_file")"
case "$version" in
  [0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "pitot-shim: pin must be one semver line, got '$version'" >&2; exit 1 ;;
esac

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$os" in
  linux|darwin) ;;
  *) echo "pitot-shim: unsupported OS $os" >&2; exit 1 ;;
esac
arch="$(uname -m)"
case "$arch" in
  x86_64|amd64) arch=amd64 ;;
  arm64|aarch64) arch=arm64 ;;
  *) echo "pitot-shim: unsupported arch $arch" >&2; exit 1 ;;
esac

cache_root="${PITOT_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/pitot}"
slot_dir="$cache_root/$version/$os-$arch"
slot="$slot_dir/pitot"

if [ ! -x "$slot" ]; then
  no_hydrate="${PITOT_NO_HYDRATE:-0}"
  if [ -n "$no_hydrate" ] && [ "$no_hydrate" != "0" ]; then
    echo "pitot-shim: version $version is pinned by .pitot/version but $slot is absent and hydration is disabled (PITOT_NO_HYDRATE=1) (absence-fails-closed-and-named)" >&2
    exit 1
  fi
  host="${PITOT_GET_HOST:-get.operatorstack.systems}"
  case "$host" in
    http://*|https://*) base="$host" ;;
    *) base="https://$host" ;;
  esac
  archive="pitot_${version}_${os}_${arch}.tar.gz"
  mkdir -p "$slot_dir"
  lock="$slot_dir/.hydrate-lock"
  tries=0
  while ! mkdir "$lock" 2>/dev/null; do
    tries=$((tries + 1))
    if [ "$tries" -gt 200 ]; then
      echo "pitot-shim: hydration lock $lock held past deadline; remove it if the holder crashed" >&2
      exit 1
    fi
    sleep 0.15
    if [ -x "$slot" ]; then
      break
    fi
  done
  if [ ! -x "$slot" ]; then
    tmp="$(mktemp -d "$slot_dir/.hydrating-XXXXXX")"
    cleanup() { rm -rf "$tmp"; rmdir "$lock" 2>/dev/null || true; }
    trap cleanup EXIT
    if ! curl -fsSL "$base/pitot/dl/$version/$archive" -o "$tmp/$archive"; then
      echo "pitot-shim: version $version is pinned by .pitot/version but $slot is absent and the download from $base failed (absence-fails-closed-and-named)" >&2
      exit 1
    fi
    if ! curl -fsSL "$base/pitot/dl/$version/checksums.txt" -o "$tmp/checksums.txt"; then
      echo "pitot-shim: checksums.txt download failed (nothing-executes-unverified)" >&2
      exit 1
    fi
    want="$(awk -v f="$archive" '$2 == f { print $1 }' "$tmp/checksums.txt")"
    if command -v sha256sum >/dev/null 2>&1; then
      got="$(sha256sum "$tmp/$archive" | awk '{print $1}')"
    else
      got="$(shasum -a 256 "$tmp/$archive" | awk '{print $1}')"
    fi
    if [ -z "$want" ] || [ "$got" != "$want" ]; then
      echo "pitot-shim: checksum mismatch for $archive — refusing to install (nothing-executes-unverified)" >&2
      exit 1
    fi
    tar -xzf "$tmp/$archive" -C "$tmp"
    found="$(find "$tmp" -type f -name pitot | head -n 1)"
    if [ -z "$found" ]; then
      echo "pitot-shim: release archive carries no pitot binary" >&2
      exit 1
    fi
    chmod 0755 "$found"
    mv "$found" "$slot"
    rm -rf "$tmp"
    rmdir "$lock" 2>/dev/null || true
    trap - EXIT
  else
    rmdir "$lock" 2>/dev/null || true
  fi
fi

# Text-file-busy can surface briefly when a concurrent hydration just wrote
# the slot; retry a few times before giving up.
tries=0
while :; do
  "$slot" "$@"
  code=$?
  if [ "$code" -ne 126 ] || [ "$tries" -ge 30 ]; then
    exit "$code"
  fi
  tries=$((tries + 1))
  sleep 0.1
done
`

// shimPowerShell is the committed Windows shim (same contract, PowerShell
// dialect; zip archives).
const shimPowerShell = `# Pitot repo shim — generated by 'pitot init'. Reads the committed pin
# (.pitot/version), hydrates that exact release into the user cache when
# absent (sha256-verified), and execs it. Upgrades rewrite the pin in a
# reviewed diff; this file never changes behavior on its own.
$ErrorActionPreference = "Stop"

$here = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$pinFile = Join-Path $here ".pitot\version"
if (-not (Test-Path $pinFile)) {
  Write-Error "pitot-shim: missing .pitot/version (absence-fails-closed-and-named)"
  exit 1
}
$version = (Get-Content $pinFile -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') {
  Write-Error "pitot-shim: pin must be one semver line, got '$version'"
  exit 1
}

$arch = if ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture -eq "Arm64") { "arm64" } else { "amd64" }
$cacheRoot = if ($env:PITOT_CACHE_DIR) { $env:PITOT_CACHE_DIR } else { Join-Path $env:LOCALAPPDATA "pitot" }
$slotDir = Join-Path $cacheRoot "$version\windows-$arch"
$slot = Join-Path $slotDir "pitot.exe"

if (-not (Test-Path $slot)) {
  if ($env:PITOT_NO_HYDRATE -and $env:PITOT_NO_HYDRATE -ne "0") {
    Write-Error "pitot-shim: version $version is pinned by .pitot/version but $slot is absent and hydration is disabled (PITOT_NO_HYDRATE=1) (absence-fails-closed-and-named)"
    exit 1
  }
  $hostName = if ($env:PITOT_GET_HOST) { $env:PITOT_GET_HOST } else { "get.operatorstack.systems" }
  $base = if ($hostName -match '^https?://') { $hostName } else { "https://$hostName" }
  $archive = "pitot_${version}_windows_${arch}.zip"
  New-Item -ItemType Directory -Force -Path $slotDir | Out-Null
  $tmp = Join-Path $slotDir (".hydrating-" + [System.IO.Path]::GetRandomFileName())
  New-Item -ItemType Directory -Path $tmp | Out-Null
  try {
    Invoke-WebRequest -Uri "$base/pitot/dl/$version/$archive" -OutFile (Join-Path $tmp $archive)
    Invoke-WebRequest -Uri "$base/pitot/dl/$version/checksums.txt" -OutFile (Join-Path $tmp "checksums.txt")
    $want = (Select-String -Path (Join-Path $tmp "checksums.txt") -Pattern ([regex]::Escape($archive))).Line.Split(" ")[0]
    $got = (Get-FileHash -Algorithm SHA256 (Join-Path $tmp $archive)).Hash.ToLower()
    if (-not $want -or $got -ne $want.ToLower()) {
      Write-Error "pitot-shim: checksum mismatch for $archive — refusing to install (nothing-executes-unverified)"
      exit 1
    }
    Expand-Archive -Path (Join-Path $tmp $archive) -DestinationPath $tmp
    $found = Get-ChildItem -Path $tmp -Recurse -Filter "pitot.exe" | Select-Object -First 1
    if (-not $found) {
      Write-Error "pitot-shim: release archive carries no pitot.exe"
      exit 1
    }
    Move-Item -Path $found.FullName -Destination $slot
  } finally {
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
  }
}

& $slot @args
exit $LASTEXITCODE
`

// printHydrationStatus renders the doctor's view of the binary substrate:
// pin, slot, shim, and pin-vs-running drift.
func printHydrationStatus(stdout io.Writer) {
	fmt.Fprintln(stdout, "hydration:")
	root := "."
	if found, err := config.FindRoot("."); err == nil {
		root = found
	}
	pin, err := hydrate.Pin(root)
	if err != nil {
		fmt.Fprintf(stdout, "  pin: none (%s absent or invalid)\n", hydrate.PinPath)
		return
	}
	fmt.Fprintf(stdout, "  pin: %s (%s)\n", pin, hydrate.PinPath)
	if slot, slotErr := hydrate.Slot(pin); slotErr == nil {
		if _, statErr := os.Stat(slot); statErr == nil {
			fmt.Fprintf(stdout, "  slot: present (%s)\n", slot)
		} else {
			fmt.Fprintf(stdout, "  slot: absent — the next shim invocation hydrates %s\n", pin)
		}
	}
	if _, err := os.Stat(filepath.Join(filepath.FromSlash(shimDir), "pitot")); err == nil {
		fmt.Fprintf(stdout, "  shim: present (%s/pitot)\n", shimDir)
	} else {
		fmt.Fprintf(stdout, "  shim: absent — run 'pitot init' to write %s/pitot\n", shimDir)
	}
	if running := releaseVersion(); running != pin {
		fmt.Fprintf(stdout, "  drift: running binary is %s but the pin is %s — the shim would run %s\n", running, pin, pin)
	}
}

// writeSubstrate ensures the repository substrate exists: the version pin
// (when the running binary carries a release identity) and the committed
// shims. Existing files are left untouched — the substrate is ensured by
// whoever arrives first, owned by no one.
func writeSubstrate(stdout io.Writer, binaryVersion string) ([]string, error) {
	var written []string

	pinPath := filepath.FromSlash(hydrate.PinPath)
	if _, err := os.Stat(pinPath); os.IsNotExist(err) {
		if binaryVersion == "dev" || binaryVersion == "" {
			fmt.Fprintf(stdout, "note: no %s written — this is an unreleased pitot build; pin a released version yourself to enable the shim\n", hydrate.PinPath)
		} else {
			if err := hydrate.WritePin(".", binaryVersion); err != nil {
				return nil, err
			}
			written = append(written, hydrate.PinPath)
		}
	}

	shims := map[string]string{
		filepath.Join(shimDir, "pitot"):     shimPOSIX,
		filepath.Join(shimDir, "pitot.ps1"): shimPowerShell,
	}
	if err := os.MkdirAll(filepath.FromSlash(shimDir), 0o755); err != nil {
		return nil, fmt.Errorf("pitot init: create %s: %w", shimDir, err)
	}
	for path, body := range shims {
		if _, err := os.Stat(path); err == nil {
			continue
		}
		mode := os.FileMode(0o644)
		if !strings.HasSuffix(path, ".ps1") {
			mode = 0o755
		}
		if err := os.WriteFile(path, []byte(body), mode); err != nil {
			return nil, fmt.Errorf("pitot init: write %s: %w", path, err)
		}
		written = append(written, filepath.ToSlash(path))
	}
	return written, nil
}
